### ISSUE TITLE
unaccounted confounders

### ISSUE THREAD

**Issue by francogrex** [lbenz730/world_cup_2022#2]
Good work. But I've seen your previous predictions for Euro 2021 and also seeing the current progress in Qatar 11/2022 I believe that your model is incomplete and there are other confounding factors that you should be accounting for. What those are, I cannot really tell you, it needs exploration.

**Comment by lbenz730** [comment]
I mean sure, any model can improve but of 58 public models it's doing pretty well (5th).

https://twitter.com/Futbolmetrix1/status/1597360450454159360?s=20&t=Nph5CqdxPCPwWdgoxlJNzQ
